config/urls.py
from django.conf import settings
from django.conf.urls.static import static

from django.contrib import admin
from django.urls import path, include

from rest_framework_swagger.views import get_swagger_view

schema_view = get_swagger_view(title='TMS API')
urlpatterns = [
    path(
        'admin/', admin.site.urls
    ),
    path(
        'api/doc/', schema_view
    ),
    path(
        'api/',
        include(
            ('tms.account.urls', 'account'),
            namespace='account'
        )
    ),
    path(
        'api/',
        include(
            ('tms.info.urls', 'info'),
            namespace='info'
        )
    ),
    path(
        'api/',
        include(
            ('tms.route.urls', 'route'),
            namespace='route'
        )
    ),
    path(
        'api/',
        include(
            ('tms.vehicle.urls', 'vehicle'),
            namespace='vehicle'
        )
    ),
    path(
        'api/',
        include(
            ('tms.order.urls', 'order'),
            namespace='order'
        )
    ),
    path(
        'api/',
        include(
            ('tms.business.urls', 'business'),
            namespace='business'
        )
    ),
    path(
        'api/',
        include(
            ('tms.security.urls', 'security'),
            namespace='security'
        )
    ),
    path(
        'api/warehouse/',
        include(
            ('tms.warehouse.urls', 'warehouse'),
            namespace='warehouse'
        )
    ),
    path(
        'api/',
        include(
            ('tms.notification.urls', 'notification'),
            namespace='notification'
        )
    ),
    path(
        'api/hr/',
        include(
            ('tms.hr.urls', 'hr'),
            namespace='hr'
        )
    ),
    path(
        'api/finance/',
        include(
            ('tms.finance.urls', 'finance'),
            namespace='finance'
        )
    ),
]

if settings.DEBUG:
    urlpatterns += static(
        settings.MEDIA_URL,
        document_root=settings.MEDIA_ROOT
    )

tms/security/urls.py
from django.conf.urls import url, include
from django.urls import path

from rest_framework.routers import DefaultRouter
from .import views as v

router = DefaultRouter(trailing_slash=False)
router.register(
    r'company-policy',
    v.CompanyPolicyViewSet,
    base_name='company-policy'
)
router.register(
    r'questions',
    v.QuestionViewSet,
    base_name='questions'
)
router.register(
    r'security/tests',
    v.TestViewSet,
    base_name='tests'
)
router.register(
    r'security/test-results',
    v.TestResultViewSet,
    base_name='test-results'
)
router.register(
    r'security/programs',
    v.SecurityLearningProgramViewSet,
    base_name='programs'
)
router.register(
    r'security/libraries',
    v.SecurityLibraryViewSet,
    base_name='libraries'
)
router.register(
    r'security/check-plans',
    v.SecurityCheckPlanViewSet,
    base_name='security-check-plans'
)
router.register(
    r'security/issues',
    v.SecurityIssueViewSet,
    base_name='security-issues'
)

# router.register(
#     r'security-knowledge',
#     v.SecurityKnowledgeViewSet,
#     base_name='security-knowledge'
# )

urlpatterns = [
    url(r'^', include(router.urls)),
    path('security/libraries/upload-attachments/', v.SecurityLibraryAttachmentUploadView.as_view()),
    path('security/libraries/delete-attachments/<int:pk>/', v.SecurityLibraryAttachmentDeleteView.as_view()),
    path('apps/company-policy/<int:policy_id>', v.get_company_policy, name='app-company-policy'),
    path('apps/tests/<int:test_id>/', v.get_test_template, name='app-test'),
    path('apps/tests/<int:test_id>/<int:question_id>/vote/', v.answer_question, name='answer-question'),
    path('security/issue-types/', v.SecurityIssueTypeOptionsAPIView.as_view()),
]

tms/security/views.py
import jwt
from django.utils import timezone
from django.conf import settings
from django.http import Http404
from django.urls import reverse
from django.shortcuts import render, get_object_or_404, redirect
from rest_framework import status, viewsets
from rest_framework.views import APIView
from rest_framework.parsers import MultiPartParser
from rest_framework.permissions import AllowAny
from rest_framework.decorators import action
from rest_framework.response import Response

from ..core import constants as c
from ..core.serializers import ChoiceSerializer

# models
from . import models as m
from ..account.models import User

# serializers
from . import serializers as s


class CompanyPolicyViewSet(viewsets.ModelViewSet):

    queryset = m.CompanyPolicy.objects.all()
    serializer_class = s.CompanyPolicySerializer

    def get_queryset(self):
        queryset = self.queryset.all()
        departments = self.request.query_params.get('departments', None)
        if departments:
            departments = departments.split(',')
            departments = [int(department) for department in departments]
            queryset = self.queryset.filter(departments__id__in=departments)

        return queryset

    def create(self, request):
        author = request.data.pop('author', None)
        departments = request.data.pop('departments', [])
        if author is not None:
            pass
        else:
            author = request.user

        serializer = s.CompanyPolicySerializer(
            data=request.data,
            context={
                'author': author,
                'departments': departments
            }
        )

        serializer.is_valid(raise_exception=True)
        serializer.save()
        return Response(
            serializer.data,
            status=status.HTTP_200_OK
        )

    def update(self, request, pk=None):
        instance = self.get_object()
        author = request.data.pop('author', None)
        departments = request.data.pop('departments', [])
        if author is not None:
            pass
        else:
            author = request.user

        serializer = s.CompanyPolicySerializer(
            instance,
            data=request.data,
            context={
                'author': author,
                'departments': departments
            }
        )

        serializer.is_valid(raise_exception=True)
        serializer.save()
        return Response(
            serializer.data,
            status=status.HTTP_200_OK
        )

    @action(detail=False, url_path="short")
    def get_short_policies(self, request):
        """
        this api is called in driver app
        """
        page = self.paginate_queryset(
            m.CompanyPolicy.published_content.filter(
                departments=request.user.profile.department
            )
        )
        serializer = s.ShortCompanyPolicySerializer(
            page, context={'user': request.user}, many=True
        )
        return self.get_paginated_response(serializer.data)

    @action(detail=True, url_path="status")
    def get_policy_status(self, request, pk=None):
        policy = self.get_object()
        return Response(
            s.CompanyPolicyStatusSerializer(policy).data,
            status=status.HTTP_200_OK
        )

    @action(detail=True, url_path="users")
    def get_users(self, request, pk=None):
        policy = self.get_object()
        page = self.paginate_queryset(policy.reads.filter(is_read=True))
        serializer = s.CompanyPolicyReadSerializer(page, many=True)
        return self.get_paginated_response(serializer.data)

    @action(detail=False, url_path="policy-options")
    def get_policy_options(self, request):
        ret = []
        for (value, text) in c.COMPANY_POLICY_TYPE:
            ret.append({
                'value': value,
                'text': text
            })

        return Response(
            ret, status=status.HTTP_200_OK
        )

    @action(detail=True, url_path="read")
    def read_policy(self, request, pk=None):
        """
        this api is called in driver app for marking policy read state
        """
        policy = self.get_object()
        policy_read, created = m.CompanyPolicyRead.objects.get_or_create(
            policy=policy,
            user=request.user
        )

        if not created:
            policy_read.is_read = True
            policy_read.save()

        return Response(
            {
                'is_read': True
            },
            status=status.HTTP_200_OK
        )


# class SecurityKnowledgeViewSet(TMSViewSet):

#     queryset = m.SecurityKnowledge.objects.all()
#     serializer_class = s.SecurityKnowledgeSerializer

#     def create(self, request):
#         author = request.data.pop('author', None)

#         if author is not None:
#             pass
#         else:
#             author = request.user

#         serializer = s.SecurityKnowledgeSerializer(
#             data=request.data,
#             context={
#                 'author': author
#             }
#         )

#         serializer.is_valid(raise_exception=True)
#         serializer.save()
#         return Response(
#             serializer.data,
#             status=status.HTTP_200_OK
#         )

#     def update(self, request, pk=None):
#         instance = self.get_object()
#         author = request.data.pop('author', None)

#         if author is not None:
#             pass
#         else:
#             author = request.user

#         serializer = s.SecurityKnowledgeSerializer(
#             instance,
#             data=request.data,
#             context={
#                 'author': author
#             }
#         )

#         serializer.is_valid(raise_exception=True)
#         serializer.save()
#         return Response(
#             serializer.data,
#             status=status.HTTP_200_OK
#         )


class QuestionViewSet(viewsets.ModelViewSet):

    queryset = m.Question.objects.all()
    serializer_class = s.QuestionSerializer

    @action(detail=False, url_path="short")
    def get_short_list(self, request):
        page = self.paginate_queryset(m.Question.objects.all())
        serializer = s.ShortQuestionSerializer(page, many=True)
        return self.get_paginated_response(serializer.data)


class TestViewSet(viewsets.ModelViewSet):

    queryset = m.Test.objects.all()
    serializer_class = s.TestSerializer

    @action(detail=False, url_path="my-tests")
    def me(self, request):
        """
        this api is called in driver app for retrieving test
        """
        page = self.paginate_queryset(m.Test.objects.filter(appliants=request.user))
        serializer = s.ShortTestSerializer(
            page, context={'user': request.user}, many=True
        )
        return self.get_paginated_response(serializer.data)


class TestResultViewSet(viewsets.ModelViewSet):

    queryset = m.TestResult.objects.all()
    serializer_class = s.TestResultSerializer


class SecurityLearningProgramViewSet(viewsets.ModelViewSet):

    queryset = m.SecurityLearningProgram.objects.all()
    serializer_class = s.SecurityLearningProgramSerializer

    @action(detail=False, url_path="my-program")
    def me(self, request):
        page = self.paginate_queryset(m.SecurityLearningProgram.objects.filter(audiences=request.user))
        serializer = s.ShortSecurityLearningProgramSerializer(page, many=True)
        return self.get_paginated_response(serializer.data)


class SecurityLibraryViewSet(viewsets.ModelViewSet):

    queryset = m.SecurityLibrary.objects.all()
    serializer_class = s.SecurityLibrarySerializer

    def create(self, request):
        context = {
            'author': request.data.pop('author'),
            'departments': request.data.pop('departments')
        }
        serializer = s.SecurityLibrarySerializer(
            data=request.data, context=context
        )
        serializer.is_valid(raise_exception=True)
        serializer.save()
        return Response(
            serializer.data, status=status.HTTP_201_CREATED
        )

    def update(self, request, pk=None):
        instance = self.get_object()
        context = {
            'author': request.data.pop('author'),
            'departments': request.data.pop('departments')
        }
        serializer = s.SecurityLibrarySerializer(
            instance, data=request.data, context=context
        )
        serializer.is_valid(raise_exception=True)
        serializer.save()

        return Response(
            serializer.data, status=status.HTTP_200_OK
        )

    @action(detail=True, url_path="attachments")
    def get_attachments(self, request, pk=None):
        instance = self.get_object()
        return Response(
            s.ShortSecurityLibraryAttachmentSerializer(instance.attachments.all(), many=True).data,
            status=status.HTTP_200_OK
        )


class SecurityLibraryAttachmentUploadView(APIView):
    parser_classes = [MultiPartParser, ]
    permission_classes = [AllowAny]

    def post(self, request):
        data = {}
        data['library'] = request.data.pop('library')[0]
        # try:
        #     library = m.SecurityLibrary.objects.get(id=data['library'])
        #     m.SecurityLibraryAttachment.objects.filter(
        #         library=library
        #     ).delete()
        # except m.SecurityLibrary.DoesNotExist:
        #     pass

        for _, data_file in request.data.items():
            data['attachment'] = data_file
            serializer = s.SecurityLibraryAttachmentSerializer(data=data)
            serializer.is_valid(raise_exception=True)
            serializer.save()
        return Response({
            'msg': 'Successfully uploaded'
        }, status=status.HTTP_200_OK)


class SecurityLibraryAttachmentDeleteView(APIView):

    def delete(self, request, pk, format=None):
        instance = get_object_or_404(m.SecurityLibraryAttachment, id=pk)
        instance.delete()

tms/security/templates/security/policy.html
<html>
  <head>
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <style>
      h1 {
        text-align: center;
        margin: 10px 0;
        font-size: 30px;
        padding: 10px;
      }
      .sub_wrap {
        padding: 1.5em 0;
        padding: 10px;
        border-top: 1px solid #000000;
        border-bottom: 1px solid #000000;
        font-size: 1em;
      }
      .sub_wrap span {
        font-weight: bold;
        font-size: 1em;
      }
      .sub_content {
        font-size: 0.8em;
        clear: both;
        padding: 10px 10px 10px 0;
      }
      .sub_wrap div {
        float: none;
      }
      .clear {
        clear: both;
      }
      @media screen and (min-width: 767px) {
        .sub_wrap div {
          float: left;
          margin-right: 20px;
        }
        .sub_wrap div:first-child {
          margin-left: 15px;
        }
        .clear {
          clear: both;
          float: none !important;
        }
      }
    </style>
  </head>
  <body>
    <h1>{{title}}</h1>
    <div class="sub_wrap">
      <div>
        <span>发布时间</span>: {{ published_on | date:'Y-m-d'}}
      </div>
      <div>
        <span>作者</span>: {{ author }}
      </div>
      <div>
        <span>适用范围</span>: {{ departments }}
      </div>
      <div class="clear"></div>
    </div>

    <div class="sub_content">
    {{content | safe}}
    </div>
  </body>
</html>

tms/security/templates/security/test.html
<html>
  <head>
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <style>
      .btn {
        display: inline-block;
        padding: 6px 12px;
        margin-bottom: 0;
        font-size: 15px;
        font-weight: bold;
        line-height: 1.42857143;
        text-align: center;
        white-space: nowrap;
        vertical-align: middle;
        -ms-touch-action: manipulation;
        touch-action: manipulation;
        cursor: pointer;
        -webkit-user-select: none;
        -moz-user-select: none;
        -ms-user-select: none;
        user-select: none;
        background-image: none;
        border: 1px solid transparent;
        border-radius: 4px;
        text-decoration: none;
      }
      .start_wrap {
        text-align: center;
        height: 100vh;
      }
      .start_btn {
        color: #fff;
        background-color: #5cb85c;
        border-color: #4cae4c;
        position: relative;
        top: 50%;
      }
      .submit_btn {
        color: #fff;
        background-color: #5cb85c;
        border-color: #4cae4c;
      }
      form {
        position: relative;
        top: 20%;
      }
      h3 {
        font-size: 20px;
      }
      .result_h3 {
        text-align: center;
        margin-top: 20px;
      }
      .error_msg {
        color: red;
        font-size: 12px;
        padding: 0;
        margin: 0;
        margin-bottom: 5px;
      }
      label {
        font-size: 18px;
      }
      span {
        font-weight: bold;
      }
      hr.dashed-style {
        border-style: dashed;
      }
      hr.double-style {
        border-style: double;
      }
      hr:last-child {
        border: none;
      }
    </style>
  </head>
  <body>
    {% if is_finished %}
    <h3 class="result_h3">测试结果</h3>
    <hr class="double-style"/>
    <div><span>考试时间</span>：{{ started_on | date:'Y-m-d' }}</div>
    <div><span>完成时间</span>: {{ finished_on | date:'Y-m-d' }}</div>
    <div><span>考试分数</span>: {{ point }} / {{ full_point }}</div>
    <hr class="double-style"/>
    <div>
      {% for result in results %}
        {{ result.question.question | safe }}
        {% if result.question.question_type == 0 %}
          {% if result.is_correct %}
            <div><input type="radio" name="options" value="1" id="answer1" checked disabled><label for="answer1">&nbsp;True</label></div>
            <div><input type="radio" name="options" value="0" id="answer2" disabled><label for="answer2">&nbsp;False</label></div>
          {% else %}
            <div><input type="radio" name="options" value="1" id="answer1" disabled><label for="answer1">&nbsp;True</label></div>
            <div><input type="radio" name="options" value="0" id="answer2" checked disabled><label for="answer2">&nbsp;False</label></div>
          {% endif %}
        {% elif result.question.question_type == 1 %}
          {% for choice in result.question.choices %}
            {% if forloop.counter0 in result.answers %}
              <div><input type="radio" name="answers" value="{{ forloop.counter0 }}" id="single{{ forloop.counter0 }}" checked disabled><label for="single{{ forloop.counter0}}">&nbsp;{{ choice }}</label></div>
            {% else %}
              <div><input type="radio" name="answers" value="{{ forloop.counter0 }}" id="single{{ forloop.counter0 }}" disabled><label for="single{{ forloop.counter0}}">&nbsp;{{ choice }}</label></div>
            {% endif %}
          {% endfor %}
        {% else %}
          {% for choice in result.question.choices %}
            {% if forloop.counter0 in result.answers %}
              <div><input type="checkbox" name="answers" value="{{ forloop.counter0 }}" id="multiple{{ forloop.counter0 }}" checked disabled><label for="multiple{{ forloop.counter0}}">&nbsp;{{ choice }}</label></div>
            {% else %}
              <div><input type="checkbox" name="answers" value="{{ forloop.counter0 }}" id="multiple{{ forloop.counter0 }}" disabled><label for="multiple{{ forloop.counter0}}">&nbsp;{{ choice }}</label></div>
            {% endif %}
          {% endfor %}
        {% endif %}
        <hr class="dashed-style"/>
      {% endfor %}
    </div>
    {% else %}
      {% if not is_started %}
      <div class="start_wrap">
        <a class="btn start_btn" href="{% url 'security:app-test' test.id %}?start=1&username={{username}}&token={{token}}">Start Test</a>
      </div>
      {% else %}
        <form action="{% url 'security:answer-question' test.id question.id %}?&username={{username}}&token={{token}}" method="post" onsubmit="return validateForm()">
          {% csrf_token %}
          <h3>{{ question.question | safe }}</h3>
          {% if question.question_type == 0 %}
            <div><input type="radio" name="answers" value="1" id="answer1"><label for="answer1">&nbsp;True</label></div>
            <div><input type="radio" name="answers" value="0" id="answer2"><label for="answer2">&nbsp;False</label></div>
          {% elif question.question_type == 1 %}
            {% for choice in question.choices %}
              <div><input type="radio" name="answers" value="{{ forloop.counter0 }}" id="single{{ forloop.counter0 }}"><label for="single{{ forloop.counter0}}">&nbsp;{{ choice }}</label></div>
            {% endfor %}
          {% else %}
            {% for choice in question.choices %}
            <div><input type="checkbox" name="answers" value="{{ forloop.counter0 }}" id="multiple{{ forloop.counter0 }}"><label for="multiple{{ forloop.counter0}}">&nbsp;{{ choice }}</label></div>
            {% endfor %}
          {% endif %}
          <br />
          <p id="error-msg" class="error_msg"></p>
          <input type="hidden" name="username" value="{{username}}">
          <input class="btn submit_btn" type="submit" value="Vote">
        </form>
      {% endif %}
    {% endif %}
    <script>
      function validateForm() {
        var checkboxes = document.getElementsByName("answers");
        var numberOfCheckedItems = 0;
        for(var i = 0; i < checkboxes.length; i++)
        {
          if(checkboxes[i].checked)
            numberOfCheckedItems++;
        }
        if (numberOfCheckedItems == 0) {
          document.getElementById('error-msg').innerHTML = '请选择一个选项';
          return false;
        }
        return true
      }
    </script>
  </body>
</html>